### ISSUE TITLE
Only lancer

### ISSUE THREAD

**Issue by Kumicoo** [Monstertera/tera-script#1]
What you uploaded is only lancer. Where is the rest?

and also - thank you so much for sharing!!!!!

**Comment by Monstertera** [comment]
> What you uploaded is only lancer. Where is the rest?
> 
> and also - thank you so much for sharing!
Not sharing, just showing that i actually have the scripts, also that lancer script is outdated and won't work, if u want more contact me on discord and i can sell to you.

**Comment by Stardustmaterial** [comment]
Stop leeching off others, dumbtards. Find a job.

**Comment by Kumicoo** [comment]
> > What you uploaded is only lancer. Where is the rest?
> > and also - thank you so much for sharing!
> > Not sharing, just showing that i actually have the scripts, also that lancer script is outdated and won't work, if u want more contact me on discord and i can sell to you.

Ah i see! Sorry, i misunderstood wrong. Thought this was supposed to be a full share! Apologies! :)
